version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: mysql-contenedorcrud
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3001:3001
    networks:
      - my_network
    
volumes:
  mysql-volume:

networks:
  my_network: